---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

pem_agent_config_path: "{{ pem_agent_base_dir }}/etc/agent.cfg"
pem_agent_certificate_directory: /root/.pem

pemagent_CN: pemagent-{{ inventory_hostname }}
pemagent_clientcert_owner: "{{ pem_group|default('root') }}"
pemagent_clientcert_group: "{{ pem_group|default('root') }}"
pemagent_clientcert_service: "{{ pemagent_CN }}"
pemagent_csr_path: "{{ pgbapi_ssl_dir }}/{{ pemagent_clientcert_service }}.csr"
pemagent_privatekey_path: "{{ pgbapi_ssl_dir }}/{{ pemagent_clientcert_service }}.key"
pemagent_certificate_path: "{{ pgbapi_ssl_dir }}/{{ pemagent_clientcert_service }}.crt"
