---

# Copyright Â© EnterpriseDB Corporation

- name: Ensure that this instance is a replica
  assert:
    msg: "Postgres is not running as a replica"
    that:
      - role|contains('replica')
      - cluster_facts.pg_is_in_recovery

- name: Ensure that primary_conninfo is configured
  assert:
    msg: "No primary_conninfo configured in recovery.conf"
    that:
      - cluster_facts.replica.get('primary_conninfo', '') != ''

# TODO
#
# If we just started Postgres, we waited until it reached a consistent
# recovery point and started accepting connections (postgres-monitor),
# but it may still be performing archive recovery and not have started
# streaming, so we can't just fail if pg_stat_wal_receiver is empty.
#
# We should check if primary_slot_name is configured and, if so, check
# that the correct upstream instance actually has a slot by that name.
# This is not straightforward, because we may not have initialised the
# correct upstream instance yet.
