---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

repmgr_failover: automatic

repmgr_use_slots: 1

default_repmgr_cluster_cleanup_interval: '36 5 * * *'

repmgr_conf_settings: []
