---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: Install main client configuration file
  template:
    src: client.conf.j2
    dest: "{{ openvpn_config }}.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Note openvpn restart required
