---

# Â© Copyright EnterpriseDB UK Limited 2015-2023 - All rights reserved.

- name: Enable watchdog udev rule
  copy:
    content: |
      KERNEL=="watchdog", OWNER="{{ watchdog_user }}", GROUP="{{ watchdog_group }}", MODE="660"
    dest: /etc/udev/rules.d/99-watchdog.rules
    owner: root
    group: root
    mode: "0644"

- name: Enable softdog kernel module
  copy:
    content: |
      softdog
    dest: /etc/modules-load.d/softdog.conf
    owner: root
    group: root
    mode: "0644"

- name: Load softdog kernel module
  modprobe:
    name: softdog

- name: Ensure correct ownership of /dev/watchdog
  file:
    path: /dev/watchdog
    owner: "{{ watchdog_user }}"
    group: "{{ watchdog_group }}"
    mode: "0660"
