---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

# To use 2ndQuadrant repositories after March 2020, it was necessary to
# have the 2ndquadrant-repository-keys package installed. That package
# created the directory /usr/share/2ndquadrant-repository-keys. We used to
# install the package here if it wasn't already installed; however, as
# the 2ndQuadrant repositories are being retired, installing the package
# is no longer supported. So if you haven't redeployed since before March
# 2020, you will now be unable to use 2ndQuadrant repositories at all.

- name: Install 2ndquadrant-repository-keys
  raw:
    if [[ ! -d /usr/share/2ndquadrant-repository-keys ]]; then
      for f in /etc/apt/sources.list.d/2ndquadrant-*; do
        if [[ -e "$f" ]]; then
          echo "2ndQuadrant repositories detected but no repository keys present";
          echo "This installation can no longer be updated";
          exit 1;
        fi;
      done;
    fi
  args:
    executable: /bin/bash

  register: repository_keys_installed
  changed_when: repository_keys_installed.stdout.strip() != ''
