---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

selfsigned: "{{ not ssl_cert_authentication|default('yes') }}"

ssl_user: root
ssl_group: root
ssl_service: "{{ inventory_hostname }}"
# check_result_varname: "{{ (ssl_service == inventory_hostname)|ternary('default', ssl_service) }}"

default_ssl_server_cert_expiry: +365d

ssl_dir: "/etc/tpa"

csr_path: "{{ ssl_dir }}/{{ ssl_service }}.csr"
ca_path: "{{ ssl_dir }}/root.crt"
privatekey_path: "{{ ssl_dir }}/{{ ssl_service }}.key"
certificate_path: "{{ ssl_dir }}/{{ ssl_service }}.crt"
