---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

- name: Install BDR-specific configuration file
  template:
    src: bdr.conf.j2
    dest: "{{ _include_dir }}/3333-bdr.conf"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: 0644
  notify:
    - Note Postgres reload required
