---

# Copyright Â© 2ndQuadrant Limited <info@2ndquadrant.com>

- name: Install BDR configuration file on BDR nodes
  template:
    src: camo.conf.j2
    dest: "{{ _include_dir }}/3334-camo.conf"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: 0644
  notify:
    - Note Postgres restart required
