---
# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

- name: Update postgres restart config fact with preload library settings
  include_role:
    name: config/add_to_obj
  vars:
    object_varname: postgres_restart_config
    object_contents:
      shared_preload_libraries: "{{ _preload_list|join(', ') }}"
