---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# If any replica references a slot on this instance that does not exist,
# we create it, even though we can't guarantee that the WAL required by
# the replica still exists.

- name: Create replication slot
  postgresql_query:
    conninfo: "{{ postgres_dsn }}"
    queries:
      - text: "{{ create_slot_query }}"
        args:
          - "{{ slot_name }}"
  become_user: "{{ postgres_user }}"
  become: yes
  vars:
    create_slot_query: >
      SELECT pg_create_physical_replication_slot(%s
        {%- if postgres_version is version('9.6', '>=') -%}
          , TRUE
        {%- endif -%}
      )
