---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- meta: flush_handlers

# We don't want to restart all running etcds at the same time, so we
# loop over the list of all etcd instances and have each one restart
# itself in turn.

- name: Start or restart etcd service one-by-one on etcd instances
  include_tasks: restart-one.yml
  with_items: "{{ groups['role_etcd'] }}"
  when:
    inventory_hostname == item
  tags: [service, restart]
