---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: Grant required privileges to {{ harp_dcs_user }}
  postgresql_privs:
    port: "{{ postgres_port }}"
    login_user: "{{ postgres_user }}"
    database: "{{ bdr_database }}"
    privs: "{{ item.privs }}"
    type: "{{ item.type }}"
    objs: "{{ item.objs }}"
    schema: "{{ item.schema }}"
    roles: "{{ harp_dcs_user }}"
    grant_option: yes
    state: present
  with_items:
    - type: table
      privs: SELECT
      schema: bdr
      objs: consensus_kv_data
    - type: table
      privs: SELECT
      schema: bdr
      objs: local_node_summary
    - type: function
      privs: EXECUTE
      schema: bdr
      objs: "consensus_kv_fetch(text)"
    - type: function
      privs: EXECUTE
      schema: bdr
      objs: "consensus_kv_store(text:jsonb:jsonb:int)"
    - type: function
      privs: EXECUTE
      schema: bdr
      objs: "bdr_version_num()"
    - type: function
      privs: EXECUTE
      schema: bdr
      objs: "get_raft_status()"
    - type: function
      privs: EXECUTE
      schema: bdr
      objs: "peer_state_name(oid)"
    - type: function
      privs: EXECUTE
      schema: bdr
      objs: "monitor_group_raft()"
  become_user: "{{ postgres_user }}"
  become: yes
  when:
    inventory_hostname == first_bdr_primary
