---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

CA_CN: "{{ cluster_name }}.CA"

local_ssl_dir: "{{ cluster_dir }}/ssl"

local_ca_certificate_path: "{{ local_ssl_dir }}/CA.crt"
local_ca_csr_path: "{{ local_ssl_dir }}/CA.csr"
local_ca_privatekey_path: "{{ local_ssl_dir }}/CA.key"

ca_path: "{{ ssl_dir }}/root.crt"
