---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: Check if the BDR group has been created already
  postgresql_query:
    conninfo: '{{ bdr_node_dsn }}'
    queries:
      - text: SELECT node_name FROM bdr.bdr_nodes WHERE node_name = %s
        args:
          - "{{ bdr_node_name }}"
  register: bdr2_node_tuples
  become_user: "{{ postgres_user }}"
  become: yes

- name: Create the BDR group if necessary
  postgresql_query:
    conninfo: '{{ bdr_node_dsn }}'
    queries:
      - text: SELECT bdr.bdr_group_create(local_node_name := %s, node_external_dsn := %s)
        args:
          - "{{ bdr_node_name }}"
          - "{{ bdr_node_dsn }}"
  when:
    inventory_hostname == first_bdr_primary and
    bdr2_node_tuples.rowcount == 0
  become_user: "{{ postgres_user }}"
  become: yes

- name: Wait for the creating node to become ready
  postgresql_query:
    conninfo: '{{ bdr_node_dsn }}'
    query: >-
      SELECT bdr.bdr_node_join_wait_for_ready()
  when:
    inventory_hostname == first_bdr_primary and
    bdr2_node_tuples.rowcount == 0
  become_user: "{{ postgres_user }}"
  become: yes
