---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

- include_role: name=pkg/add_to_list
  vars:
    list_contents: "{{
      (ansible_os_family == 'RedHat'
        and edb_repositories is empty
        and tpa_2q_repositories is empty)
        and default_list_contents|select('match', 'repmgr_')|list is empty
      | ternary(
        default_list_contents|map('replace', 'repmgr', 'repmgr_')|list,
        default_list_contents,
      )
      }}"
    default_list_contents: "{{
        repmgr_packages[postgres_flavour]
        |packages_for(ansible_os_family, repmgr_package_version)
      }}"
  when:
    failover_manager in ['repmgr', 'efm']
    and 'postgres' in role
    and 'bdr' not in role
