---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

# We don't check for failover_manager == 'repmgr' here, because we use
# repmgr to clone replicas even when using EFM.

- include_role: name=pkg/add_to_list
  vars:
    list_contents: "{{
        repmgr_packages[postgres_family_extended]
        |packages_for(ansible_os_family, repmgr_package_version)
      }}"
  when: >
    'postgres' in role
    and 'bdr' not in role
