---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

# Handle calls to the health API

# GET /health: returns HTTP status code 200 only when PostgreSQL is up and running

- name: Get the current Patroni cluster health status using the `/health` API
  uri:
    method: GET
    url: "{{ _patroni_api_scheme }}://{{ inventory_hostname }}:{{ patroni_listen_port }}/health"
    body_format: json
    url_username: "{{ patroni_restapi_user }}"
    url_password: "{{ vars['%s_password' % patroni_restapi_user] }}"

    # This option is not supported until ansible core 2.11
    # ca_path: "{{ patroni_ssl_enabled|ternary(_patroni_ssl_ca_path, omit) }}"
    validate_certs: no

  register: patroni_health_api_output
