---

# Â© Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.

# Handle calls to the Patroni liveness API

# GET /liveness: returns HTTP status code 200 if Patroni heartbeat loop is properly running
# and 503 if the last run was more than ttl seconds ago on the primary or 2*ttl on the replica.
# Could be used for livenessProbe.

- name: Check if Patroni is ready to start serving requests by calling the `/liveness` API
  uri:
    method: GET
    url: "{{ _patroni_api_scheme }}://{{ inventory_hostname }}:{{ patroni_listen_port }}/cluster"
    body_format: json
    url_username: "{{ patroni_restapi_user }}"
    url_password: "{{ vars['%s_password' % patroni_restapi_user] }}"

    # This option is not supported until ansible core 2.11
    # ca_path: "{{ patroni_ssl_enabled|ternary(_patroni_ssl_ca_path, omit) }}"
    validate_certs: no

    # This is needed to avoid blocking API calls in case there is a
    # proxy, e.g. for downloading packages
    use_proxy: no

  register: patroni_liveness_api_output
