---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

- include_role:
    name: "repmgr/{{ repmgr_installation_method|default(postgres_installation_method) }}"
  when: >
    'postgres' in role
    and platform not in ['shared']
    and task_selector|permits(repmgr_installation_method)

- include_role: name=repmgr/common
  when: >
    'postgres' in role

- set_fact:
    initialise_replication: true
