---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- meta: flush_handlers

- name: Start or restart haproxy
  service:
    name: haproxy
    state: "{{ haproxy_service_end_state|default('started') }}"
  become_user: root
  become: yes
  when: >
    'haproxy' in role
  tags: [service, restart]
