---

# Copyright Â© EnterpriseDB Corporation

- name: Enable sysstat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: >-
      ENABLED="true"
  register: sysstat

- name: Update frequency of collection
  template:
    src: sysstat-debian
    dest: /etc/cron.d/sysstat
    owner: root
    group: root
    mode: 0644

- name: Restart sysstat if required
  service:
    name: sysstat
    state: restarted
  when:
    sysstat is changed
