---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# by default, don't install pg-backup-api
enable_pg_backup_api: false

pg_backup_api_installation_method: pkg
pg_backup_api_src_dir: /opt/postgres/src/pg-backup-api
pg_backup_api_build_dir: /opt/postgres/build/pg-backup-api

pgbapi_packages:
  Debian:
    - pg-backup-api
    - "{{ python_pkg_prefix }}-cryptography"
    - apache2
  RedHat:
    - pg-backup-api
    - "{{ python_pkg_prefix }}-cryptography"
    - httpd
    - mod_ssl
