---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

haproxy_packages:
  Debian: &debian_haproxy_packages
    - haproxy
  RedHat:
    - haproxy
  Ubuntu: *debian_haproxy_packages
