---

# Copyright Â© 2ndQuadrant Limited <info@2ndquadrant.com>

# These tasks are executed on any instance that needs to be backed up.
#
# Backups for an instance are configured in /etc/barman.d/name.conf on
# the designated backup server. When we first set up backups, we must
# set active=false (which we do in a separate file) and then activate
# the backups in barman/final.
#
# We also need to handle the special case of detaching /var/lib/barman
# from a working instance and attaching it to a new instance, where we
# would have /var/lib/barman/name but not /etc/barman.d/name.conf.

- name: Check if Barman backup directory exists
  stat:
    path: "{{ _barman_backup_directory }}"
  delegate_to: "{{ this_barman }}"
  register: backup_dir

- name: Install Barman client configuration file
  template:
    src: barman.d.conf.j2
    dest: "{{ _config_file }}"
    owner: barman
    group: barman
    mode: 0600
  delegate_to: "{{ this_barman }}"
  vars:
    active: "{{ backup_dir.stat.exists }}"
    target: "{{ parent_inventory_hostname|default(inventory_hostname) }}"

- name: Set up a cron job to take regular backups
  cron:
    user: barman
    cron_file: /etc/cron.d/{{ backup_name }}
    name: Backup from server {{ backup_name }}
    minute: "{{ _barman_backup_interval[0] }}"
    hour: "{{ _barman_backup_interval[1] }}"
    day: "{{ _barman_backup_interval[2] }}"
    month: "{{ _barman_backup_interval[3] }}"
    weekday: "{{ _barman_backup_interval[4] }}"
    job: >
      /etc/tpa/barman-home-ok && /usr/bin/barman backup {{ backup_name }}
    state: present
  delegate_to: "{{ this_barman }}"

