---

## Barman server-wide defaults (/etc/barman.conf)

default_barman_log_file: /var/log/barman/barman.log

default_barman_backup_method: rsync
default_barman_parallel_jobs: 1
default_barman_reuse_backup: link
default_barman_backup_options: concurrent_backup
default_barman_immediate_checkpoint: false

default_barman_compression: pigz
default_barman_network_compression: false

default_barman_basebackup_retry_times: 3
default_barman_basebackup_retry_sleep: 30

default_barman_minimum_redundancy: 3
default_barman_retention_policy: RECOVERY WINDOW OF 4 WEEKS
default_barman_last_backup_maximum_age: 1 WEEK

## Automatic backup schedule

default_barman_backup_interval: '0 4 * * wed,sat'
