---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

efm_packages:
  Debian: &debian_efm_packages
    - "edb-efm{{ efm_versionNN }}"
  RedHat:
    - "edb-efm{{ efm_versionNN }}"
  Ubuntu: *debian_efm_packages
