---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

_repmgr_cluster_cleanup_interval: "{{ (repmgr_cluster_cleanup_interval|default(default_repmgr_cluster_cleanup_interval)).split(' ')|list }}"
