---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

- name: Stop/update/restart etcd
  when: >
    'etcd' in role
  block:
  - include_role: name=etcd/restart
    vars:
      etcd_service_end_state: stopped

  - include_role: name=etcd/pkg
    vars:
      allow_package_upgrades: yes

  - include_role: name=etcd/restart
    vars:
      etcd_service_end_state: started
