---

# Copyright Â© EnterpriseDB Corporation

- include_tasks: docker_images.yml
  vars:
    docker_image_list: "{{
      docker_instances|map(attribute='image')|unique|list
    }}"
  tags: docker

- name: Create docker networks
  docker_network:
    name: "{{ item.name }}"
    scope: "{{ item.labels|default(omit) }}"
    labels: "{{ item.labels|default(omit) }}"
    enable_ipv6: "{{ item.enable_ipv6|default(omit) }}"
    ipam_config: "{{ item.ipam_config|default(omit) }}"
  with_items:
    - "{{ docker_networks|default([]) }}"
  tags: docker

- name: Provision docker containers
  include_tasks: docker_container.yml
  with_items: "{{ docker_instances }}"
  tags: docker

- name: Set instance variables and IP
  set_fact:
    instance_vars: "{{
      instance_vars|default([])|union([
        addresses|combine({
          'Name': item.item.Name,
          'node': item.item.node,
          'vars': addresses|combine(item.item|export_vars),
          'platform': 'docker',
        })
      ])
    }}"
  with_items:
    "{{ docker_container_results }}"
  loop_control:
    label: >-
      {{ item.item.Name }}
  vars:
    addresses: "{{ item.item|ip_addresses }}"
