---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- include_role: name=pkg/add_to_list
  vars:
    list_contents: "{{ package_lists|flatten }}"
    package_lists:
      - "{{ default_unwanted_packages[ansible_distribution] }}"
      - "{{ unwanted_packages[ansible_distribution]|default([]) }}"
