---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

# We want to install the sudo package unless sudo is already available
# (it might be provided by some other package, which we don't want to
# mess with).

- name: Check if sudo is available
  shell: >
    if ! command -v sudo >/dev/null 2>&1; then echo yes; fi
  register: needs_sudo
  changed_when: False
  check_mode: no

- include_role: name=pkg/add_to_list
  vars:
    list_contents: "{{ package_lists|flatten }}"
    package_lists:
      - "{{ default_packages['common'] }}"
      - "{{ packages['common']|default([]) }}"
      - "{{ default_packages[ansible_distribution] }}"
      - "{{ packages[ansible_distribution]|default([]) }}"
      - "{{ (needs_sudo.stdout.strip() == 'yes')|ternary(['sudo'], []) }}"
