---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# There aren't recent-enough etcd packages available in the default
# repositories for Debian, and none at all for RedHat. The following
# custom packages (etcd and etcdctl packaged separately) are available
# from an EDB repository.

etcd_packages:
  Debian:
    - harp-etcd
    - harp-etcdctl
  RedHat:
    - harp-etcd
    - harp-etcdctl
