---

# Copyright Â© 2ndQuadrant Limited <info@2ndquadrant.com>

- name: Note Postgres reload required
  set_fact:
    postgres_service_end_state: reloaded

- name: Note Postgres restart required
  set_fact:
    postgres_service_end_state: restarted
