---

# Â© Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.

- name: Note Postgres reload required
  set_fact:
    postgres_service_end_state: reloaded

- name: Note Postgres restart required
  set_fact:
    postgres_service_end_state: restarted

- name: Restart Postgres when SSL configuration changes
  listen: Note postgres SSL configuration changed
  set_fact:
    postgres_service_end_state: restarted
