---

# Copyright Â© 2ndQuadrant Limited <info@2ndquadrant.com>

- name: Include postgres-pre-update hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/postgres-pre-update.yml"
  tags: always

- include_tasks: "{{ postgres_installation_method }}.yml"
  tags: always

- name: Include postgres-post-update hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/postgres-post-update.yml"
  tags: always

- fail: msg="Please redeploy to update extensions built from source"
  when: >
    install_from_source is not empty

- include_role: name=postgres/restart
  tags: always
