---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# Set the openvpn IP address for each host based on its node number. I
# wish there were a more graceful way to do this. (Note that we cannot
# assume that the openvpn server will be assigned the .1 address.)

- name: Record openvpn IP address
  set_fact:
    openvpn_ip: "{{ vpn_network|ipaddr('network')|regex_replace('\\.[0-9]*$', '.'~node) }}"
