---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- when: "'barman' in role"
  block:
  - include_role: name=pkg/add_to_list
    vars:
      list_contents: "{{
          barman_packages|packages_for(ansible_os_family, barman_package_version)
        }}"
    when:
      barman_installation_method == 'pkg'

  - include_role:
      name: postgres/pkg
      tasks_from: list-client-packages.yml

  # We expect pg_receivewal to be installed, but the EPAS client rpm does
  # not include it (although the deb package does), so we have to install
  # the server package as a temporary workaround. 2ndQPostgres 13 also
  # needs the same workaround.

  - include_role: name=pkg/add_to_list
    vars:
      redhat_workaround_packages:
        RedHat:
          - "{{ postgres_package_name }}{{ postgres_versionNN }}-server"
      list_contents: "{{
          redhat_workaround_packages
          |packages_for(ansible_os_family, postgres_package_version)
        }}"
    when:
      ansible_os_family == 'RedHat'
      and (postgresql_flavour == 'epas'
        or (postgresql_flavour == 'pgextended'
            and postgres_version is version('13', '>=')))
