---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- include_tasks: list-packages.yml
  vars:
    list_varname: _all_pem_server_packages

- include_role: name=pkg/install
  vars:
    package_list_name: "PEM server packages"
    package_list: "{{ _all_pem_server_packages }}"
