---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

_ssh_key_dir: "{{ ssh_key_dir|default(cluster_dir+'/keys') }}"
_ssh_key_name: "{{ ssh_key_name|default('id_'+ssh_username) }}"
_ssh_key_comment: "{{ ssh_key_name|default(ssh_username ~'@'~ cluster_name) }}"
