---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

repmgr_git_url: git://github.com/EnterpriseDB/repmgr.git
repmgr_git_ref: "REL5_2_STABLE"
repmgr_git_reference_repo: ""

repmgr_src_dir: /opt/postgres/src/repmgr
repmgr_build_dir: /opt/postgres/build/repmgr
repmgr_install_dir: "{{ postgres_install_dir|default('/opt/postgres/' + postgres_version) }}"
