---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# All our startup tasks will go into /etc/tpa/rc.local, which will be
# invoked from the system-wide /etc/rc.local (whose contents we have
# less control over, especially because sysadmins are likely to edit
# that file in unpredictable ways).

- name: Create /etc/tpa/rc.local
  copy:
    force: no
    dest: /etc/tpa/rc.local
    owner: root
    group: root
    mode: 0755
    content: |
      #!/bin/bash
      #
      # TPA startup tasks.

- name: Create /etc/rc.local if needed
  copy:
    force: no
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
    content: |
      #!/bin/sh
      #
      exit 0

- name: Ensure that /etc/rc.local is executable
  file:
    path: /etc/rc.local
    follow: yes
    mode: 0755

- name: Make /etc/rc.local invoke /etc/tpa/rc.local
  lineinfile:
    path: /etc/rc.local
    mode: 0755
    line: >-
      test -x /etc/tpa/rc.local && /etc/tpa/rc.local
    state: present
    insertbefore: "exit 0"

- name: Enable rc-local service
  systemd:
    name: rc-local
    enabled: yes

- name: Set permissions and ownership for tpaexec.log
  file:
    path: /var/log/tpaexec.log
    mode: 0644
    owner: root
    group: root

- block:
  - name: Create /etc/tpa/rebuild-scripts
    file:
      path: /etc/tpa/rebuild-scripts
      owner: root
      group: root
      state: directory
      mode: 0755
  - name: Create /etc/tpa/rebuild-sources.sh
    copy:
      src: rebuild-sources.sh
      dest: /etc/tpa/rebuild-sources.sh
      mode: 0755
  when:
    postgres_installation_method == 'src'
    or repmgr_installation_method == 'src'
    or install_from_source is not empty
