---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

- include_role:
    name: pgbouncer/service
  when: >
    task_selector|permits('service')

- include_role:
    name: pgbouncer/restart
  when: >
    task_selector|permits('service', 'restart')
