---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- meta: flush_handlers

- name: Start or restart pgbouncer
  service:
    name: pgbouncer
    state: "{{ pgbouncer_service_end_state|default('started') }}"
  become_user: root
  become: yes
  when: >
    'pgbouncer' in role
  tags: [service, restart]
