---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: Run pgbench on database {{ pgbench_dbname }}
  command: >
    {{ postgres_bin_dir }}/pgbench -h {{ postgres_host }} -p {{ postgres_port }} {{ pgbench_opts }} {{ pgbench_dbname }}
  register: pgbench
  become_user: "{{ postgres_user }}"
  become: yes

- include_role: name=test tasks_from=output.yml
  vars:
    output_file: "{{ pgbench_output }}"
    content: |
      {{ pgbench.stdout }}
  when: pgbench_output|default('') != ''
