---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: Configure {{ target_repo_name }} repository
  raw: |
    set -x
    tmpfile=$(mktemp)
    trap 'rm -f "$tmpfile"' EXIT
    tee "$tmpfile" <<EOF
    {{ content }}
    EOF
    content_sum=$(sha256sum "$tmpfile")
    path_sum=$(sha256sum "{{ path }}")
    if [ ! -f "{{ path }}" ] ;then
      mv "$tmpfile" "{{ path }}" && exit 200
    elif [ "${content_sum/ */}" != "${path_sum/ */}" ] ;then
      mv "$tmpfile" "{{ path }}" && exit 201
    fi
  register: _create_repo
  failed_when:
    _create_repo.rc > 0 and _create_repo.rc < 200
  changed_when:
    _create_repo.rc >= 200
  notify: "Repo configuration changed"
