---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

- name: Create BDR node
  postgresql_query:
    conninfo: "{{ bdr_node_dsn }}"
    queries:
      - text: SELECT bdr.create_node(node_name := %s, local_dsn := %s, node_kind := %s) AS node_id
        args:
          - "{{ bdr_node_name }}"
          - "{{ bdr_node_dsn }}"
          - "{{ role|bdr_node_kind }}"
  become_user: "{{ postgres_user }}"
  become: yes
  register: new_bdr_node
  changed_when: true
