---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

requirements:
  common:
    - git
    - flex
    - bison
    - ccache
    - "{{ python_pkg_prefix }}-setuptools"
  Debian:
    - libreadline-dev
    - zlib1g-dev
    - libssl-dev
    - build-essential
    - libipc-run-perl
    - libselinux1-dev
    - libxslt1-dev
    - libxml2-dev
    - libedit-dev
    - libpam0g-dev
    - krb5-multidev
    - libkrb5-dev
    - liblz4-dev
  RedHat:
    - autoconf
    - automake
    - binutils
    - gcc
    - gcc-c++
    - gdb
    - glibc-devel
    - libtool
    - make
    - pkgconf
    - pkgconf-m4
    - pkgconf-pkg-config
    - readline-devel
    - zlib-devel
    - openssl-devel
    - pam-devel
    - libxml2-devel
    - libxslt-devel
    - perl-Test-Simple
    - perl-App-cpanminus
    - krb5-devel
    - lz4-devel
    - libcurl-devel
