---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- include_tasks: privatekey.yml

- name: Check if server certificate exists
  stat:
    path: "{{ certificate_path }}"
  register: crt_check
  check_mode: no

- name: "Verify server certificate {{ certificate_path }}"
  include_role:
    name: sys/ssl
    tasks_from: verify
  when: crt_check.stat.exists

- include_tasks: "{{
    selfsigned|ternary(
    'selfsigned.yml', 'certificate.yml'
    )
  }}"
  when: >
    not crt_check.stat.exists
    or not cert_verify_passed

- name: Copy CA certificate to target instances
  copy:
    src: "{{ local_ca_certificate_path }}"
    dest: "{{ ca_path }}"
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: 0644
    force: no
  register: cert_copy
  when:
    not selfsigned
  notify:
    - Note SSL configuration changed

- name: Set path to CA certificate(s)
  set_fact:
    ssl_ca_file: "{{ ssl_ca_file|default(ca_path) }}"
  when:
    not selfsigned

- name: Set paths to SSL key and certificate
  set_fact:
    ssl_key_file: "{{ ssl_key_file|default(privatekey_path) }}"
    ssl_cert_file: "{{ ssl_cert_file|default(certificate_path) }}"

- include_role:
    name: sys/ssl
    tasks_from: security
  vars:
    ssl_dirs: [ssl_dir]
  when:
    not crt_check.stat.exists
    or cert_copy is changed

- name: Verify certificate was generated correctly
  include_role:
    name: sys/ssl
    tasks_from: verify
  vars:
    privatekey_path: "{{ ssl_key_file }}"
    certificate_path: "{{ ssl_cert_file }}"
    ca_path: "{{ ssl_ca_file|default(None) }}"

- name: Bail if certificate does not pass verification checks
  fail:
    msg: >
      Post creation verification checks did not pass for Server certificate.
      Please run with verbose flags to determine the reason.
  when: not cert_verify_passed

# Calls to sys/ssl roles will overwrite these variables, so we
# export them, so they can be used by the caller as more specific names

- name: Set SSL file locations
  action: set_fact
  args:
    "{{ check_result_varname }}_ssl_ca_file": "{{
        (not selfsigned and not legacy_ssl_enabled)|ternary(ssl_ca_file, '')
      }}"
    "{{ check_result_varname }}_ssl_crl_file": "{{ ssl_crl_file|default('') }}"
    "{{ check_result_varname }}_ssl_cert_file": "{{
        legacy_ssl_enabled|ternary('/etc/tpa/' + cluster_name + '.crt', ssl_cert_file)
      }}"
    "{{ check_result_varname }}_ssl_key_file": "{{
        legacy_ssl_enabled|ternary('/etc/tpa/' + cluster_name + '.key', ssl_key_file)
      }}"
