---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

local_ssl_dir: "{{ cluster_dir }}/ssl"
local_ca_certificate_path: "{{ local_ssl_dir }}/CA.crt"
local_ca_privatekey_path: "{{ local_ssl_dir }}/CA.key"
local_csr_path: "{{ local_ssl_dir }}/{{ inventory_hostname }}/{{ ssl_service }}.csr"
local_certificate_path: "{{ local_ssl_dir }}/{{ inventory_hostname }}/{{ ssl_service }}.crt"
