---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: Disable manage_ssh_hostkeys by default
  set_fact:
    manage_ssh_hostkeys: "{{
      manage_ssh_hostkeys|default(False)
    }}"
