---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

_pgpassfile: "{{ pgpassfile|default('~%s/.pgpass' % postgres_user) }}"
_pgpass_owner: "{{ pgpass_owner|default(postgres_user) }}"
_pgpass_group: "{{ pgpass_group|default(postgres_group) }}"
_pgpass_users: "{{ pgpass_users|default(default_pgpass_users) }}"
