---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: restart zabbix-agent
  service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
    enabled: yes
  become: yes
