---

# Copyright Â© 2ndQuadrant Limited <info@2ndquadrant.com>

- assert:
    msg: "Ansible 2.6.x is required"
    that:
      - ansible_version.major == 2
      - ansible_version.minor == 6
  tags: prereqs

- name: Ensure that local dependencies are installed
  become: no
  assert:
    msg: "Please install {{ item }} locally"
    that: path != ''
  with_items:
    - flock
  vars:
    path: "{{ lookup('pipe', 'command -v {{ item }} || true') }}"
  run_once: yes

- name: Ensure that password generation works correctly
  become: no
  assert:
    msg: "Please fix lib/password (e.g., install pwgen)"
    that:
      - password != ''
  vars:
    password: "{{ lookup('pipe', '{{ tpa_dir }}/architectures/lib/password || true') }}"
  run_once: yes
