---
# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

- name: Gather facts about the patroni cluster
  patroni_cluster_facts:
    cluster: "{{ cluster_name }}"
    config_dir: "{{ patroni_etc }}"
    patronictl_path: "{{ patronictl_path }}"
    locale: "{{
      user_locale|default(
          (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 8)
          |ternary('en_US.utf-8', 'C.UTF-8')
        )
      }}"
  become: yes
  become_user: root
