---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

- name: Include post-deploy hook
  include_tasks: "{{ hook }}"
  when:
    lookup('first_found', dict(files=hook, skip=True))
  vars:
    hook: "{{ cluster_dir }}/hooks/post-deploy.yml"
  tags: always
