---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# We used to generate a cluster_name.{key,crt} keypair earlier. If these
# files exist, and we don't need to configure certificate authentication
# (which won't work with self-signed host certificates), we just use the
# existing keys for backwards compatibility.

- name: Check if legacy server certificate is installed
  raw: >
    test -f /etc/tpa/{{ cluster_name }}.crt
  failed_when: false
  changed_when: false
  register: old_crt_check
  check_mode: no

- name: Set legacy ssl fact if certificate is present
  set_fact:
    legacy_ssl_enabled: "{{ old_crt_check.rc == 0 }}"
