---

# Â© Copyright EnterpriseDB UK Limited 2015-2025 - All rights reserved.

# pgd-cli packages for v1
pgdcli1_packages:
  Debian: &debian_pgdcli1_package
    - edb-pgd-cli
  RedHat:
    - edb-pgd-cli
  Ubuntu: *debian_pgdcli1_package
  SUSE:
    - edb-pgd-cli
# pgd-cli packages for v5 and above
pgdcli_packages:
  Debian: &debian_pgdcli_package
    - edb-pgd{{ bdr_version }}-cli
  RedHat:
    - edb-pgd{{ bdr_version }}-cli
  Ubuntu: *debian_pgdcli_package
  SUSE:
    - edb-pgd{{ bdr_version }}-cli

bdr_utilities_packages:
  Debian: &debian_bdrutilities_package
    - edb-bdr-utilities
  RedHat:
    - edb-bdr-utilities
  Ubuntu: *debian_bdrutilities_package
  SUSE:
    - edb-bdr-utilities

pgdcli_extra_packages:
  Debian: &debian_pgdcli_extra_packages
    - bash-completion
  RedHat: *debian_pgdcli_extra_packages
  Ubuntu: *debian_pgdcli_extra_packages
  SUSE: *debian_pgdcli_extra_packages
