---

# Copyright Â© EnterpriseDB Corporation

- name: Ensure openvpn configuration is present
  assert:
    msg: "Please define vpn_network in CIDR format"
    that:
      - vpn_network is defined

# Perform local initialisation tasks (generating keys and certificates).

- include_tasks: local.yml

# Perform instance initialisation tasks.

- name: Create openvpn configuration directory
  file:
    path: "{{ openvpn_config }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Install key and certificate files on each instance
  copy:
    src: "{{ _local_cert_dir }}/{{ item.name }}"
    dest: "{{ openvpn_config }}/"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - name: ca.crt
      mode: "0644"
    - name: "{{ inventory_hostname }}.crt"
      mode: "0644"
    - name: "{{ inventory_hostname }}.key"
      mode: "0600"
    - name: ta.key
      mode: "0600"
  notify:
    - Note openvpn restart required
