---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

pgbouncer_packages:
  Debian: &debian_pgbouncer_packages
    - pgbouncer
  RedHat:
    - pgbouncer
  Ubuntu: *debian_pgbouncer_packages
