---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# By default, we install packages with `state: present` so that packages
# are installed once during the first deploy, and then left alone. This
# works for packages with or without explicit version specifications.
#
# To upgrade packages, define `allow_package_upgrades: yes`. This will
# use `state: latest` with unversioned packages (i.e., those for which
# xxx_package_version is unset), and `state: present` for versioned
# packages (which error out with `state: latest`).
#
# (Note that the upgrade mode does not support check_install_only.)

- include_tasks:
    file: "{{ _install_only|ternary('install.yml', 'upgrade.yml') }}"
  vars:
    _install_only: "{{
        not allow_package_upgrades|default(False)|bool
        or check_install_only|default(False)|bool
      }}"
