---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

# Any instance might need Postgres client packages, so there's nothing
# to double-check here.

- include_role: name=pkg/add_to_list
  vars:
    list_contents: "{{ _packages|flatten }}"
    _packages:
    - "{{ postgres_client_packages[postgres_family]|packages_for(ansible_distribution, postgres_package_version) }}"
    - "{{ psycopg2_packages|packages_for(ansible_distribution) }}"
