---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

- name: Install extra packages for Postgres source installations
  package:
    name: >
      {{ package_lists|flatten }}
    state: latest
  vars:
    package_lists:
    - "{{ src_extra_packages|packages_for(ansible_os_family) }}"
    - "{{ psycopg2_packages|packages_for(ansible_os_family) }}"
  tags: pkg
