---

# Copyright Â© 2ndQuadrant Limited <info@2ndquadrant.com>

- name: Create openvpn client configuration directory
  file:
    path: "{{ openvpn_config }}/ccd"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set permissions on openvpn configuration directory
  file:
    path: "{{ openvpn_config }}/.."
    state: directory
    mode: o+x

# XXX We shouldn't use play_hosts here.

- name: Install client-configuration-database files
  template:
    src: ccd.j2
    dest: "{{ openvpn_config }}/ccd/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ play_hosts|difference(inventory_hostname) }}"

- name: Install the DH parameters
  copy:
    src: "{{ _local_cert_dir }}/dh2048.pem"
    dest: "{{ openvpn_config }}/dh2048.pem"
    owner: root
    group: root
    mode: 0644
  notify:
    - Note openvpn restart required

- name: Install main server configuration file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_config }}.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Note openvpn restart required

- meta: flush_handlers

- name: Start or restart openvpn on the server
  service:
    name: "{{ openvpn_service_name }}"
    state: "{{ openvpn_service_end_state|default('started') }}"
