---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

harp_packages:
  "2":
    Debian: &debian_harp2_packages
      - harp-manager
    RedHat:
      - harp-manager
    Ubuntu: *debian_harp2_packages

harp_proxy_packages:
  "2":
    Debian: &debian_harp2_proxy_packages
      - harp-proxy
    RedHat:
      - harp-proxy
    Ubuntu: *debian_harp2_proxy_packages
