---

# Copyright Â© 2ndQuadrant Limited <info@2ndquadrant.com>

_config_file: "/etc/barman.d/{{ backup_name }}.conf"

_barman_backup_directory: "/var/lib/barman/{{ backup_name }}"

_barman_log_file: "{{ barman_log_file|default(default_barman_log_file) }}"
_barman_backup_method: "{{ barman_backup_method|default(default_barman_backup_method) }}"
_barman_parallel_jobs: "{{ barman_parallel_jobs|default(default_barman_parallel_jobs) }}"
_barman_reuse_backup: "{{ barman_reuse_backup|default(default_barman_reuse_backup) }}"
_barman_backup_options: "{{ barman_backup_options|default(default_barman_backup_options) }}"
_barman_immediate_checkpoint: "{{ barman_immediate_checkpoint|default(default_barman_immediate_checkpoint) }}"
_barman_compression: "{{ barman_compression|default(default_barman_compression) }}"
_barman_network_compression: "{{ barman_network_compression|default(default_barman_network_compression) }}"
_barman_basebackup_retry_times: "{{ barman_basebackup_retry_times|default(default_barman_basebackup_retry_times) }}"
_barman_basebackup_retry_sleep: "{{ barman_basebackup_retry_sleep|default(default_barman_basebackup_retry_sleep) }}"
_barman_minimum_redundancy: "{{ barman_minimum_redundancy|default(default_barman_minimum_redundancy) }}"
_barman_retention_policy: "{{ barman_retention_policy|default(default_barman_retention_policy) }}"
_barman_last_backup_maximum_age: "{{ barman_last_backup_maximum_age|default(default_barman_last_backup_maximum_age) }}"
_barman_backup_interval: "{{ (barman_backup_interval|default(default_barman_backup_interval)).split(' ')|list }}"
