---

# Â© Copyright EnterpriseDB UK Limited 2015-2024 - All rights reserved.

# Add hugepages=N and transparent_hugepage=never to GRUB_CMDLINE_LINUX
# in /etc/default/grub and run update-grub.
#
# Because it's fiddly to try to add to GRUB_CMDLINE_LINUX in place, and
# because /etc/default/grub is documented to be a shell script that is
# source'd, we can just add an extra line to it.

- name: Set kernel commandline in /etc/default/grub
  shell: >
    source /etc/default/grub;
    if ! [[ "$GRUB_CMDLINE_LINUX" =~ 'transparent_hugepage=' && "$GRUB_CMDLINE_LINUX" =~ 'hugepage=' ]];
    then echo 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX hugepages={{ nr_hugepages }} transparent_hugepage={{ transparent_hugepage }}"' >> /etc/default/grub;
    else echo unchanged;
    fi
  args:
    executable: /bin/bash
  register: cmdline
  changed_when: cmdline.stdout != 'unchanged'
  vars:
    sysctls: "{{ sysctl_defaults|combine(sysctl_values) }}"
    nr_hugepages: "{{ sysctls['vm.nr_hugepages'] }}"
  when:
    platform not in ['docker', 'lxd']
    and target_container_type is not defined

- name: Run grub2-mkconfig
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when:
    cmdline is changed
    and platform not in ['docker', 'lxd']
    and target_container_type is not defined
