---

# Â© Copyright EnterpriseDB UK Limited 2015-2022 - All rights reserved.

# Given the _name_ of a fact (e.g., "all_packages", or "_etcd_packages")
# in list_varname and a list of packages in list_contents, adds the
# given list to the _value_ of the fact.

- action: set_fact
  args:
    "{{ list_varname|mandatory }}": "{{
      vars[list_varname]|default([])
      |union(list_contents|mandatory)
    }}"
