---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

# Uploads (cluster_dir/keys/)id_user{,.pub} to ~user/.ssh.
#
# - include_role: name=sys/ssh tasks_from=install.yml
#   vars:
#     ssh_username: xxx
#     ssh_key_dir: '/some/other/dir'
#     ssh_key_name: 'id_someothername'

# We copy the files as the target user and assume that they will be
# created with the correct uid/gid. Of course, most of the time the
# directory will be created correctly by the authorized_key module.

- name: Ensure that ~{{ ssh_username }}/.ssh exists
  file:
    path: "~{{ ssh_username }}/.ssh"
    state: directory
    mode: 0700
  become_user: "{{ ssh_username }}"
  become: yes

- name: Install keypair {{ _ssh_key_name }} for user {{ ssh_username }}
  action: copy
  args: "{{ item }}"
  with_items:
    - src: "{{ _ssh_key_dir }}/{{ _ssh_key_name }}"
      dest: "~{{ ssh_username }}/.ssh/id_rsa"
      mode: 0600
    - src: "{{ _ssh_key_dir }}/{{ _ssh_key_name }}.pub"
      dest: "~{{ ssh_username }}/.ssh/id_rsa.pub"
      mode: 0640
  become_user: "{{ ssh_username }}"
  become: yes
