---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

# Locally creates a keypair named id_user in cluster_dir/keys.
#
# - include_role: name=sys/ssh tasks_from=keygen.yml
#   vars:
#     ssh_username: xxx
#     ssh_key_dir: '/some/other/dir'
#     ssh_key_name: 'id_somefilename'
#     ssh_key_comment: 'xxx@yyy'

- name: Generate ssh keypair {{ _ssh_key_name }}
  shell: >
    ( flock -n 9 || exit 99;
    test -f {{ keyfile }} && exit 0;
    test -d {{ _ssh_key_dir }} || mkdir {{ _ssh_key_dir }};
    ssh-keygen -N "" -C "{{ _ssh_key_comment }}" -f "{{ keyfile }}";
    exit 88 ) 9<{{ inventory_file }}
  args:
    creates: "{{ keyfile }}"
    executable: /bin/bash
  register: key
  failed_when:
    key.rc not in [0, 88, 99]
  changed_when:
    key.rc == 88
  become: no
  vars:
    keyfile: "{{ _ssh_key_dir }}/{{ _ssh_key_name }}"
  delegate_to: localhost
