---

# Â© Copyright EnterpriseDB UK Limited 2015-2021 - All rights reserved.

# HARP default configuration values
#
# See: https://documentation.2ndquadrant.com/harp/release/latest/configuration/
default_harp_safety_interval: 100
default_harp_maximum_lag: 1048576
default_harp_maximum_camo_lag: 1048576
default_harp_lock_duration: 15
default_harp_lock_interval: 5
default_harp_external_lock_interval: 0
